# -*- coding: utf-8 -*-
"""prime_numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EOQJhj3HgXgIakkSfOIrLArCJ5r_PJiV
"""

import numpy as np
import math
import random

def is_prime(n):
  if (n <= 1): return False
  for i in range(2, int(math.sqrt(n)) + 1):
    if(n % i == 0):
      #print(i)
      return False
  return True

find_next_prime_if_not_prime(214748364100321)

def find_next_prime_if_not_prime(n): #fajnie jakby wpisywane liczby były większe od 2 lub nawet wyżej
  if (is_prime(n)): return f"{n} is a prime number."
  else:
    next_number = n + 1
    while not is_prime(next_number):
      next_number += 1
    return f"{n} is not a prime number. The next prime is {next_number}."

def is_prime_by_probability(n, accuracy):
  if (n <= 1): return False
  if n == 2 or n == 3: return True
  if (n % 2 == 0): return False

  s = 0
  d = n - 1
  while d % 2 == 0:
    d //= 2
    s += 1

  for _ in range(accuracy):
    a = random.randint(2, n - 2)
    x = pow(a, d, n)

    if x == 1 or x == n - 1:
      continue

    for _ in range(s - 1):
      x = pow(a, 2, n)
      if x == n - 1:
        break
      else:
        return False  # Composite
  return True  # Probably prime

is_prime_by_probability(214748364100321, 100000)